<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-7R5CGPG" name="Default test" tests="5" failures="5" timestamp="19 Jan 2017 15:23:27 GMT" time="35.557" errors="0">
  <testcase name="modifySomeContact" time="6.139" classname="com.example.tests.ContactModificationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [8]: ContactData [firstname=contact-1112086347, lastname=contact-1666353661, address=contact1051014303, homephone=contact-692559088, mobilephone=contact175055145, workphone=contact-1333288848, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1505260124, secondaryphone=contact-678356476] != ContactData [firstname=contact-1112086347 contact-1666353661, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1112086347, lastname=contact-1666353661, address=contact1051014303, homephone=contact-692559088, mobilephone=contact175055145, workphone=contact-1333288848, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1505260124, secondaryphone=contact-678356476]] but found [ContactData [firstname=contact-1112086347 contact-1666353661, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [8]: ContactData [firstname=contact-1112086347, lastname=contact-1666353661, address=contact1051014303, homephone=contact-692559088, mobilephone=contact175055145, workphone=contact-1333288848, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1505260124, secondaryphone=contact-678356476] != ContactData [firstname=contact-1112086347 contact-1666353661, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1112086347, lastname=contact-1666353661, address=contact1051014303, homephone=contact-692559088, mobilephone=contact175055145, workphone=contact-1333288848, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1505260124, secondaryphone=contact-678356476]] but found [ContactData [firstname=contact-1112086347 contact-1666353661, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- modifySomeContact -->
  <testcase name="modifySomeContact" time="6.203" classname="com.example.tests.ContactModificationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [54]: ContactData [firstname=contact1576259221, lastname=, address=contact-747403043, homephone=contact-162770253, mobilephone=contact-439835560, workphone=contact-631430177, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1536314354, secondaryphone=contact406086114] != ContactData [firstname=contact1576259221 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact1576259221, lastname=, address=contact-747403043, homephone=contact-162770253, mobilephone=contact-439835560, workphone=contact-631430177, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1536314354, secondaryphone=contact406086114]] but found [ContactData [firstname=contact1576259221 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [54]: ContactData [firstname=contact1576259221, lastname=, address=contact-747403043, homephone=contact-162770253, mobilephone=contact-439835560, workphone=contact-631430177, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1536314354, secondaryphone=contact406086114] != ContactData [firstname=contact1576259221 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact1576259221, lastname=, address=contact-747403043, homephone=contact-162770253, mobilephone=contact-439835560, workphone=contact-631430177, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1536314354, secondaryphone=contact406086114]] but found [ContactData [firstname=contact1576259221 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- modifySomeContact -->
  <testcase name="modifySomeContact" time="6.246" classname="com.example.tests.ContactModificationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [13]: ContactData [firstname=contact-1360453192, lastname=contact-1182926829, address=contact624220100, homephone=contact-242571673, mobilephone=contact-814696794, workphone=contact-791286812, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2013728892, secondaryphone=contact1062528390] != ContactData [firstname=contact-1360453192 contact-1182926829, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1360453192, lastname=contact-1182926829, address=contact624220100, homephone=contact-242571673, mobilephone=contact-814696794, workphone=contact-791286812, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2013728892, secondaryphone=contact1062528390]] but found [ContactData [firstname=contact-1360453192 contact-1182926829, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [13]: ContactData [firstname=contact-1360453192, lastname=contact-1182926829, address=contact624220100, homephone=contact-242571673, mobilephone=contact-814696794, workphone=contact-791286812, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2013728892, secondaryphone=contact1062528390] != ContactData [firstname=contact-1360453192 contact-1182926829, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1360453192, lastname=contact-1182926829, address=contact624220100, homephone=contact-242571673, mobilephone=contact-814696794, workphone=contact-791286812, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2013728892, secondaryphone=contact1062528390]] but found [ContactData [firstname=contact-1360453192 contact-1182926829, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- modifySomeContact -->
  <testcase name="modifySomeContact" time="6.011" classname="com.example.tests.ContactModificationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [73]: ContactData [firstname=contact995744684, lastname=contact1322381095, address=contact1480783308, homephone=contact1708913469, mobilephone=contact440471390, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact553355572, secondaryphone=contact-619680295] != ContactData [firstname=contact995744684 contact1322381095, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact995744684, lastname=contact1322381095, address=contact1480783308, homephone=contact1708913469, mobilephone=contact440471390, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact553355572, secondaryphone=contact-619680295]] but found [ContactData [firstname=contact995744684 contact1322381095, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [73]: ContactData [firstname=contact995744684, lastname=contact1322381095, address=contact1480783308, homephone=contact1708913469, mobilephone=contact440471390, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact553355572, secondaryphone=contact-619680295] != ContactData [firstname=contact995744684 contact1322381095, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact995744684, lastname=contact1322381095, address=contact1480783308, homephone=contact1708913469, mobilephone=contact440471390, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact553355572, secondaryphone=contact-619680295]] but found [ContactData [firstname=contact995744684 contact1322381095, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- modifySomeContact -->
  <testcase name="modifySomeContact" time="6.035" classname="com.example.tests.ContactModificationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [37]: ContactData [firstname=contact-660752660, lastname=contact-578336373, address=contact-2012332159, homephone=contact-1221461582, mobilephone=, workphone=contact728457368, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=, secondaryphone=] != ContactData [firstname=contact-660752660 contact-578336373, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-660752660, lastname=contact-578336373, address=contact-2012332159, homephone=contact-1221461582, mobilephone=, workphone=contact728457368, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=, secondaryphone=]] but found [ContactData [firstname=contact-660752660 contact-578336373, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [37]: ContactData [firstname=contact-660752660, lastname=contact-578336373, address=contact-2012332159, homephone=contact-1221461582, mobilephone=, workphone=contact728457368, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=, secondaryphone=] != ContactData [firstname=contact-660752660 contact-578336373, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-660752660, lastname=contact-578336373, address=contact-2012332159, homephone=contact-1221461582, mobilephone=, workphone=contact728457368, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=, secondaryphone=]] but found [ContactData [firstname=contact-660752660 contact-578336373, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- modifySomeContact -->
</testsuite> <!-- Default test -->
