<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7R5CGPG" name="com.example.tests.ContactCreationTests" tests="5" failures="5" timestamp="16 Jan 2017 14:32:43 GMT" time="29.847" errors="0">
  <testcase name="testContactCreationWithValidData" time="5.792" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [57]: ContactData [firstname=contact497088869, lastname=contact1309119554, address=contact-108392544, homephone=contact-112425110, mobilephone=contact1210350786, workphone=contact-1425349675, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1084819745, secondaryphone=contact-1317096789] != ContactData [firstname=contact497088869 contact1309119554, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact497088869, lastname=contact1309119554, address=contact-108392544, homephone=contact-112425110, mobilephone=contact1210350786, workphone=contact-1425349675, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1084819745, secondaryphone=contact-1317096789]] but found [ContactData [firstname=contact497088869 contact1309119554, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [57]: ContactData [firstname=contact497088869, lastname=contact1309119554, address=contact-108392544, homephone=contact-112425110, mobilephone=contact1210350786, workphone=contact-1425349675, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1084819745, secondaryphone=contact-1317096789] != ContactData [firstname=contact497088869 contact1309119554, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact497088869, lastname=contact1309119554, address=contact-108392544, homephone=contact-112425110, mobilephone=contact1210350786, workphone=contact-1425349675, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1084819745, secondaryphone=contact-1317096789]] but found [ContactData [firstname=contact497088869 contact1309119554, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactCreationTests.testContactCreationWithValidData(ContactCreationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testContactCreationWithValidData -->
  <testcase name="testContactCreationWithValidData" time="6.078" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [21]: ContactData [firstname=contact-1790052112, lastname=contact1909743213, address=contact934774800, homephone=contact-296077834, mobilephone=contact1968391668, workphone=contact-1997236604, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-783719398, secondaryphone=contact-1533264804] != ContactData [firstname=contact-1790052112 contact1909743213, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1790052112, lastname=contact1909743213, address=contact934774800, homephone=contact-296077834, mobilephone=contact1968391668, workphone=contact-1997236604, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-783719398, secondaryphone=contact-1533264804]] but found [ContactData [firstname=contact-1790052112 contact1909743213, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [21]: ContactData [firstname=contact-1790052112, lastname=contact1909743213, address=contact934774800, homephone=contact-296077834, mobilephone=contact1968391668, workphone=contact-1997236604, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-783719398, secondaryphone=contact-1533264804] != ContactData [firstname=contact-1790052112 contact1909743213, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1790052112, lastname=contact1909743213, address=contact934774800, homephone=contact-296077834, mobilephone=contact1968391668, workphone=contact-1997236604, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-783719398, secondaryphone=contact-1533264804]] but found [ContactData [firstname=contact-1790052112 contact1909743213, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactCreationTests.testContactCreationWithValidData(ContactCreationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testContactCreationWithValidData -->
  <testcase name="testContactCreationWithValidData" time="5.911" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [18]: ContactData [firstname=contact-1674038233, lastname=, address=contact1178746302, homephone=contact1371623666, mobilephone=contact-1714355242, workphone=contact666015303, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact241580882, secondaryphone=contact-1655747584] != ContactData [firstname=contact-1674038233 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1674038233, lastname=, address=contact1178746302, homephone=contact1371623666, mobilephone=contact-1714355242, workphone=contact666015303, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact241580882, secondaryphone=contact-1655747584]] but found [ContactData [firstname=contact-1674038233 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [18]: ContactData [firstname=contact-1674038233, lastname=, address=contact1178746302, homephone=contact1371623666, mobilephone=contact-1714355242, workphone=contact666015303, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact241580882, secondaryphone=contact-1655747584] != ContactData [firstname=contact-1674038233 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1674038233, lastname=, address=contact1178746302, homephone=contact1371623666, mobilephone=contact-1714355242, workphone=contact666015303, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact241580882, secondaryphone=contact-1655747584]] but found [ContactData [firstname=contact-1674038233 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactCreationTests.testContactCreationWithValidData(ContactCreationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testContactCreationWithValidData -->
  <testcase name="testContactCreationWithValidData" time="6.135" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [27]: ContactData [firstname=contact-2072565575, lastname=contact-1876456754, address=contact1845670044, homephone=contact1624854252, mobilephone=contact-1941466185, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-24133975, secondaryphone=contact716074388] != ContactData [firstname=contact-2072565575 contact-1876456754, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-2072565575, lastname=contact-1876456754, address=contact1845670044, homephone=contact1624854252, mobilephone=contact-1941466185, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-24133975, secondaryphone=contact716074388]] but found [ContactData [firstname=contact-2072565575 contact-1876456754, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [27]: ContactData [firstname=contact-2072565575, lastname=contact-1876456754, address=contact1845670044, homephone=contact1624854252, mobilephone=contact-1941466185, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-24133975, secondaryphone=contact716074388] != ContactData [firstname=contact-2072565575 contact-1876456754, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-2072565575, lastname=contact-1876456754, address=contact1845670044, homephone=contact1624854252, mobilephone=contact-1941466185, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-24133975, secondaryphone=contact716074388]] but found [ContactData [firstname=contact-2072565575 contact-1876456754, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactCreationTests.testContactCreationWithValidData(ContactCreationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testContactCreationWithValidData -->
  <testcase name="testContactCreationWithValidData" time="5.931" classname="com.example.tests.ContactCreationTests">
    <failure type="java.lang.AssertionError" message="Lists differ at element [38]: ContactData [firstname=contact-685804540, lastname=contact-1139689363, address=contact-140499224, homephone=contact-288738876, mobilephone=contact-1326240510, workphone=contact567025609, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=, secondaryphone=contact2043396712] != ContactData [firstname=contact-685804540 contact-1139689363, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-685804540, lastname=contact-1139689363, address=contact-140499224, homephone=contact-288738876, mobilephone=contact-1326240510, workphone=contact567025609, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=, secondaryphone=contact2043396712]] but found [ContactData [firstname=contact-685804540 contact-1139689363, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]">
      <![CDATA[java.lang.AssertionError: Lists differ at element [38]: ContactData [firstname=contact-685804540, lastname=contact-1139689363, address=contact-140499224, homephone=contact-288738876, mobilephone=contact-1326240510, workphone=contact567025609, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=, secondaryphone=contact2043396712] != ContactData [firstname=contact-685804540 contact-1139689363, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-685804540, lastname=contact-1139689363, address=contact-140499224, homephone=contact-288738876, mobilephone=contact-1326240510, workphone=contact567025609, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=, secondaryphone=contact2043396712]] but found [ContactData [firstname=contact-685804540 contact-1139689363, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactCreationTests.testContactCreationWithValidData(ContactCreationTests.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- testContactCreationWithValidData -->
</testsuite> <!-- com.example.tests.ContactCreationTests -->
